# -*- coding: utf-8 -*-
"""aula_exercicios_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzi_ii6AOYRMm0bU--n7qRyP76nOcIzZ

## Exercício 1: Verifique se um número é positivo, negativo ou zero.
"""

numero = int(input("digite um numero: "))

if(numero < 0):
  print(numero , " é negativo")
elif(numero > 0):
  print(numero ," é positivo")
elif(numero == 0):
  print("o numero digitado é ", numero)



"""## Exercício 2: Peça dois números e exiba o maior."""

numero1 = int(input("digite o primeiro numero: "))
numero2 = int(input("digite o segundo numero: "))

if(numero1 > numero2):
  print(f"o {numero1} é maior que o {numero2}")
elif(numero2 > numero1):
  print(f"o {numero2} é maior que o {numero1}")
elif(numero1 == numero2):
  print(f"o {numero1} é igual ao {numero2}")

"""## Exercício 3: Verifique se um número é par ou ímpar."""

numero = int(input("digite um numero: "))

if(numero % 2 == 0):
  print(f"o {numero} é par")
else:
  print(f"o {numero} é impar")

"""## Exercício 4: Verifique se um ano é bissexto."""

ano = int(input("digite um ano: "))

if((ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0)):
  print(f"{ano} é bissexto")
else:
  print(f"{ano} não é bisexto")

"""## Exercício 5: Peça três números e exiba o maior."""

numero = int(input("digite o primeiro numero:"))
numero2 = int(input("digite o segundo numero:"))
numero3 = int(input("digite o terceiro numero:"))

if(numero > numero2 and numero3):
  print(f"o {numero} é maior que o {numero2} e o {numero3}")
elif(numero2 > numero and numero3):
  print(f"o {numero2} é maior que o {numero} e o {numero3}")
elif(numero3 > numero and numero2):
  print(f"o {numero3} é maior que o {numero} e o {numero2}")

"""## Exercício 6: Verifique se um usuário pode votar (idade >= 18)."""

idade = int(input("digite sua idade: "))

if(idade >= 18):
  print("pode votar")
else:
  print("não pode votar")

"""## Exercício 7: Verifique se já posso ir embora da aula de Análise de Dados sem assinar a folha."""

horas = int(input("digite que horas sao: "))
assinada = input("voce assinou a folha? (sim/não) ")

if(horas >= 22 and assinada == "sim"):
  print("pode sair")
else:
  print("nao pode sair ainda")

from datetime import datetime, time

print(datetime.now().time() >= time(00,45,0))

"""## Exercício 8: Verifique se uma senha digitada corresponde a '1234'."""

senha = input("digite sua senha:")

if senha == '1234':
  print("senha correta")
else:
  print("senha incorreta")

"""## Exercício 9: Verifique se um número está entre 10 e 50."""

numero = int(input("digite um numero: "))

if numero >= 10 and numero <= 50:
  print("esta entre 10 e 50")
else:
  print("nao esta entre 10 e 50")

"""## Exercício 10: Peça ao usuário um número e exiba 'Alto' se for maior que 100 e 'Baixo' se for menor."""

numero = int(input("digite um numero: "))

if numero > 100:
  print(f"{numero} é alto")
elif numero < 100:
  print(f"{numero} é baixo")

"""## Exercício 11: Crie um menu onde o usuário pode escolher entre somar, subtrair, multiplicar e dividir dois números."""

menu = True
while(menu):

  numero1 = int(input("digite o primeiro numero: "))
  numero2 = int(input("digite o segundo numero: "))

  print("""
  1) somar
  2) subtrair
  3) multiplicar
  4) dividir
  5) sair
  """)

  opcao = int(input("digite uma opção: "))

  if(opcao == 1):
    soma = numero1 + numero2
    print(f" a soma entre o {numero1} e o {numero2} é: {soma}")
  elif(opcao == 2):
    subtrair = numero1 - numero2
    print(f" a soma entre o {numero1} e o {numero2} é: {subtrair}")
  elif(opcao == 3):
    multiplicar = numero1 * numero2
    print(f" a soma entre o {numero1} e o {numero2} é: {multiplicar}")
  elif(opcao == 4):
    dividir = numero1 / numero2
    print(f" a soma entre o {numero1} e o {numero2} é: {dividir}")
  elif(opcao == 5):
    menu = False
  else:
    print("digite um numero valido como opção")

"""
## Exercício 12: Crie um menu para converter temperaturas entre Celsius, Fahrenheit e Kelvin."""

while True:
    print("\n=== Conversor de Temperaturas ===")
    print("1 - Celsius para Fahrenheit e Kelvin")
    print("2 - Fahrenheit para Celsius e Kelvin")
    print("3 - Kelvin para Celsius e Fahrenheit")
    print("0 - Sair")

    opcao = input("Escolha uma opção: ")

    if opcao == "0":
        print("Vlw")
        break

    temp = float(input("Digite a temperatura: "))

    if opcao == "1":
        fahrenheit = (temp * 9/5) + 32
        kelvin = temp + 273.15
        print(f"{temp}°C = {fahrenheit:.2f}°F")
        print(f"{temp}°C = {kelvin:.2f}K")
    elif opcao == "2":
        celsius = (temp - 32) * 5/9
        kelvin = celsius + 273.15
        print(f"{temp}°F = {celsius:.2f}°C")
        print(f"{temp}°F = {kelvin:.2f}K")
    elif opcao == "3":
        celsius = temp - 273.15
        fahrenheit = (celsius * 9/5) + 32
        print(f"{temp}K = {celsius:.2f}°C")
        print(f"{temp}K = {fahrenheit:.2f}°F")
    else:
        print("Opção inválida! Tente novamente.")

"""## Exercício 13: Crie um programa que traduza números de 1 a 5 para palavras (1 = um, 2 = dois...)."""

numero = int(input("Digite um número de 1 a 5: "))

match numero:
    case 1:
        print("Um")
    case 2:
        print("Dois")
    case 3:
        print("Três")
    case 4:
        print("Quatro")
    case 5:
        print("Cinco")
    case _:
        print("Número fora do intervalo!")

"""## Exercício 14: Crie um menu onde o usuário pode escolher entre exibir a data, hora ou sair."""

from datetime import datetime
import pytz
agora_utc = datetime.now(pytz.utc)
print(agora_utc)

from datetime import datetime
import pytz

menu = True

while(menu):

  print("""
      (Opcoes)
      1) data
      2) hora
      3) sair
  """)

  escolha = int(input("escolha uma opcao: "))

  match escolha:
    case 1:
      print("A data de hoje e: ",datetime.now().strftime('%d-%m-%Y'))
    case 2:
      print("A hora atual e: ",datetime.now().strftime('%H:%M:%S'))
    case 3:
      menu = False

teste = {1:["teste", "teste2"]}

print(teste[1][1])

"""## Exercício 15: Implemente um programa que identifica o dia da semana baseado em um número (1 = Segunda, 7 = Domingo)."""

dia_da_semana = [
    {"id" : 1, "dia" : "segunda"},{"id" : 2, "dia" : "terca"},{"id" : 3, "dia" : "quarta"},{"id" : 4, "dia" : "quinta"},{"id" : 5, "dia" : "sexta"},{"id" : 6, "dia" :  "sabado"},{"id" : 7, "dia" : "domingo"}
                 ]

numero = int(input("digite o dia da semana: "))

for dia in dia_da_semana:
  if numero == dia["id"]:
    print(dia["dia"])

"""## Exercício 16: Verifique se um número é par ou ímpar usando if ternário."""

numero = int(input("digite um numero: "))

mensagem = "Par" if numero % 18 == 0 else "impar"
print(mensagem)

"""## Exercício 17: Verifique se um número é positivo ou negativo usando if ternário."""

numero = int(input("digite um numero"))

"positivo" if numero > -1 else "negativo"

"""## Exercício 18: Retorne 'Adulto' se a idade for maior ou igual a 18, senão 'Menor de idade'."""

idade = int(input("digite sua idade:"))

print("Adulto" if idade >= 18 else "Menor de idade")

"""## Exercício 19: Verifique se um número é maior que 100 e retorne 'Grande' ou 'Pequeno'."""

numero = int(input("digite sua idade:"))

print("Grande" if numero > 100 else "Pequeno")

"""## Exercício 20: Retorne 'Aprovado' se a nota for maior ou igual a 7, senão 'Reprovado'."""

nota = int(input("digite sua idade:"))

print("Aprovado" if nota >= 7 else "Reprovado")

"""## Exercício 21: Imprima os números de 1 a 10 usando um laço for."""

for i in range(1,11):
  print(i)

"""## Exercício 22: Imprima os números pares de 1 a 20."""

for i in range(1,21):
  if i % 2 == 0:
    print(i)

"""## Exercício 23: Calcule a soma dos números de 1 a 100."""

soma = 0
for i in range (1,101):
  soma += i

print(soma)

"""
## Exercício 24: Imprima a tabuada do 5."""

tabuada = 5
for i in range(1,11):
  print(tabuada * i)

"""## Exercício 25: Imprima os 10 primeiros números da sequência de Fibonacci."""

var = 1
var2 = 1
soma1 = 1
for i in range(10):
  print(soma1)

  soma1 = var + var2
  var = var2
  var2 = soma1

"""## Exercício 26: Percorra uma string e imprima cada caractere."""



"""## Exercício 27: Crie um programa que peça um número e imprima sua contagem regressiva até 0."""

numero = int(input("digite sua idade:"))

while(numero > -1):
  print(numero)
  numero -= 1

"""## Exercício 28: Crie um programa que solicite 5 números ao usuário e exiba a soma deles."""

numero = input("digite 5 numero separados por espaco: \n")
numero2 = 0
numero_tranformado = list(map(int, numero.split()))

for i in numero_tranformado:
  numero2 = i + numero2

print(numero2)

"""## Exercício 29: Imprima todas as vogais de uma string digitada pelo usuário."""

vogais = ["a", "e", "i", "o", "u"]

palavra_usuario = input("digite uma palavra: \n")

for i in palavra_usuario:
  for j in vogais:
    if j == i: print(j)

"""## Exercício 30: Crie um programa que peça 5 números e exiba apenas os números pares."""

valor = input("digite 5 numeros: ")
lista = list(map(int, valor.split()))

for i in lista:
  print(i) if i % 2 == 0 else ""

"""## Exercício 31: Percorra uma lista de frutas e imprima cada uma."""

frutas = ["banana", "maca", "uva", "pera"]

for i in frutas:
  print(i)

"""## Exercício 32: Some todos os números de uma lista."""

numeros = [1,2,3,4,5,6,7]
soma = 0
for i in numeros:
  soma = soma + i
  print(soma)

print(soma)

"""## Exercício 33: Multiplique cada número de uma lista por 2 e imprima o resultado."""

numeros = [1,2,3,4,5,6,7]
lista = []
for i in numeros:
  i = i * 2
  print(i)
  lista.append(i)
  print (lista)

"""## Exercício 34: Conte quantas palavras existem em uma lista de palavras."""

lista_palavras = ["ola", "tudo",  "bem", "pessoal"]


print(len(lista_palavras))

"""## Exercício 35: Imprima cada letra de uma palavra separadamente."""

palavra = "ola, mundo!"

for i in palavra: print(i)

"""## Exercício 36: Crie uma lista com 5 números e imprima o maior."""

lista = [1,2,3,4,5,6,33,10,2,3,25]
numero = 0

for i in lista:

  if i > numero:
    numero = i

print (numero)

"""## Exercício 37: Crie uma lista e inverta a ordem dos elementos."""

lista = [1,2,3,4,5,6]

lista.reverse()

print(lista)

"""## Exercício 38: Crie uma lista com 5 nomes e remova o último nome."""

nomes = ["pedro", "joao", "ana", "Tiago", "Julio"]

nomes.pop()

print(nomes)

"""## Exercício 39: Ordene uma lista de números."""

numeros = [4,6,3,4,6,1,2,3,4]

numeros.sort()

print(numeros)

"""## Exercício 40: Crie uma lista com 5 números e exiba apenas os pares."""

numero_pares = [2, 3, 4, 5, 5, 5, 6]
numero_grandes = [23, 34, 42, 12, 55, 53, 61]

numerosfiltrados = [ num > 20 for num in numero_grandes]
numero_filtrados2 = [par for par in numero_pares if par % 2 == 0]
numero_filtrados = [i * 2 for i in numero_pares]
print(numero_filtrados2)
print(numerosfiltrados)

"""## Exercício 41: Crie uma lista e adicione um novo elemento no final."""

lista = ["pera", "uva"]

lista.append("maca")

print(lista)

"""## Exercício 42: Verifique se um número existe dentro de uma lista."""

x = int(input("digite um numero: \n"))
numero = [1, 2, 3, 4, 5, 6]

resposta = "existe" if x in numero else "nao existe"
print("existe" if x in numero else "nao existe")
print(resposta)

"""## Exercício 43: Crie uma lista de números e calcule a média."""

numero = [1, 2, 3, 4, 5, 6]
print(sum(numero))

"""## Exercício 44: Crie uma lista de nomes e converta todos para maiúsculas."""

nomes = ['impar', 'par', 'impar', 'par', 'impar', 'par']

for i in range(len(nomes)):
  nomes[i] = nomes[i].upper()

print(nomes)

"""## Exercício 45: Crie uma lista de números e remova os duplicados."""

lista = [1, 2, 1, 2, 3, 3, 4, 5 ,2,3,5,4,1,2,3]

print(set(lista))

"""## Exercício 46: Crie um dicionário com nomes de alunos e suas notas e exiba a nota de um aluno específico."""

alunos = [
    {"nome":"Ana", "idade":20, "nota":8.5},
    {"nome":"Bruno", "idade":22, "nota":7.0},
    {"nome": "Carlos", "idade": 21, "nota": 6.5},
    {"nome": "Daniela", "idade": 20, "nota": 9.0},
    {"nome": "Eduarda", "idade": 23, "nota": 5.5}
]

def mostrar_nota(nome):
  for i in alunos:
    if nome == i["nome"]:
      print(i["nota"])

aluno = input("Digite o nome de um aluno:")

mostrar_nota(aluno)

"""## Exercício 47: Adicione um novo aluno e sua nota a um dicionário.

"""

alunos = [
    {"nome":"Ana", "idade":20, "nota":8.5},
    {"nome":"Bruno", "idade":22, "nota":7.0},
    {"nome": "Carlos", "idade": 21, "nota": 6.5},
    {"nome": "Daniela", "idade": 20, "nota": 9.0},
    {"nome": "Eduarda", "idade": 23, "nota": 5.5}
]

# def adicionar_aluno(lista, nome = str, idade = int, nota = float):
#   lista.append({"nome": nome, "idade": idade, "nota": nota})

# nome = input("Digite o nome do novo aluno: \n")
# idade = int(input("Digite a idade do aluno: \n"))
# nota = float(input("Digite a nota do aluno: \n"))

# adicionar_aluno(alunos, nome, idade, nota)

for i in alunos:
  print(i["nome"], i["nota"])

"""## Exercício 48: Remova um aluno do dicionário."""

alunos = {
    'joao': 8.5,
    'maria': 9.0,
    'pedro': 7.5
}

alunos.pop("pedro")

print(alunos)

"""## Exercício 49: Percorra um dicionário e imprima suas chaves e valores."""

pessoa = {
    'nome': 'Pedro',
    'idade': 25,
    'profissao': 'Desenvolvedor'
}

for chave, valor in pessoa.items():
    print(f'{chave}: {valor}')

"""## Exercício 50: Verifique se uma chave existe no dicionário."""

chave = "nome"

usuario = {
    'nome': "pedro",
    'idade': 25,
    'tamanho': 1.68
}

for chaves in usuario.keys():
  if(chaves == chave):
    print("existe")